### PR TITLE
a small fix for shiro.is

### PR DESCRIPTION
**Pull request by ArjixGamer**
Smol fix :p

### CODE REVIEW

**Comment by ArjixGamer** [comment]
provider works fine even w/o this small fix
basically, if you copy an episode link, w/o this fix it would fail to find the anime
(yes, i know that pasting episode links will behave the same as pasting the anime link itself)

**Comment by AbdullahM0hamed** [comment]
Tried with: `anime dl -u https://shiro.is/stream/dubu-xiaoyao-episode-72` got `KeyError: status` @ArjixGamer

**Comment by ArjixGamer** [comment]
its bc the slug of the anime in that link is different from the slug of the anime in the api...
https://shiro.is/anime/dubbedu-xiaoyao

**Comment by ArjixGamer** [comment]
nothing i can do, only way for me to get the slug is from the url...
scraping the website is not an option since its a dunamic only site

**Pull request merged**
