### PR TITLE
Added arabic provider EgyAnime

### PR DESCRIPTION
**Pull request by ArjixGamer**

### CODE REVIEW

**Comment by ArjixGamer** [comment]
i also added a new extractor, its for the website clipwatching

**Comment by AbdullahM0hamed** [comment]
I think it'd be great if you handled cases like https://www.egyanime.com/watch?w=8085 by throwing a custom logging.error message to let the user know there is a copyright violation

**Comment by AbdullahM0hamed** [comment]
For `anime dl -u naruto -p egyanime -c 5` - this gets https://www.egyanime.com/movie?do=10 instead of https://www.egyanime.com/movie?w=10 which then (probably) causes it to fail to extract the final link

**Review by IguanasInPyjamas — APPROVED** [review]
I'm fine with this, final say is down to @AbdullahM0hamed due to the m3u8s. 

Tested on Windows and Linux. could not find any issues.

**Pull request merged**
