### PR TITLE
fixed animesuge

### LINKED ISSUE #665: Animesuge not working.
**Describe the bug**

Animesuge not working. 

**To reproduce**

```
anime --log-level DEBUG watch --new 'Hero Academia 5'
```

LOG
https://pastebin.ubuntu.com/p/Znqw4dTkfh/

### PR DESCRIPTION
**Pull request by ArjixGamer**
Closes #665

### CODE REVIEW

**Comment by ArjixGamer** [comment]
There is a problem with the descryptor in the NineAnimeEpisode class, it has some unicode characters at the end of the link.
To deal with mp4upload i just added some regex, there is also another server but it simply works even with those characters at the end, so i did nothing for it

IF something breaks again, it would be bc of extra unicode characters
But I can't do much about that

**Comment by queeup** [comment]
I am getting this error:

<details>
<summary>LOG</summary>

```bash
~ # anime-downloader --log-level DEBUG dl 'My Hero ACademis 5'
2021-05-09 08:19:13 LibreELEC anime_downloader.util[1] INFO anime-downloader 5.0.9
2021-05-09 08:19:13 LibreELEC anime_downloader.util[1] DEBUG Platform: Linux-5.10.27-armv7l-with
2021-05-09 08:19:13 LibreELEC anime_downloader.util[1] DEBUG Python 3.9.1
2021-05-09 08:19:13 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
2021-05-09 08:19:13 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG GET https://animesuge.io/ajax/anime/search
2021-05-09 08:19:13 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'params': {'keyword': 'My Hero ACademis 5'}}
2021-05-09 08:19:13 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19'}
2021-05-09 08:19:13 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
send: b'GET /ajax/anime/search?keyword=My+Hero+ACademis+5 HTTP/1.1\r\nHost: animesuge.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 09 May 2021 08:19:14 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d303af6cade45b3fe61cda3a575ea1fa71620548353; expires=Tue, 08-Jun-21 08:19:13 GMT; path=/; domain=.animesuge.io; HttpOnly; SameSite=Lax
header: X-Frame-Options: SAMEORIGIN
header: Content-Encoding: gzip
header: x-dmc: m1
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 09f1ce979f000038b07ea75000000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=PScrUhuMeRjQWOXwko0Bwy5FFAtuJVi8N2e3uHHTkAYoOg21j6P4b0nSBbj%2F27kbpbUw2DfmIuYBE5xUq%2FFrdB9P6UjswAI8SvalHI8%3D"}],"group":"cf-nel","max_age":604800}
header: NEL: {"report_to":"cf-nel","max_age":604800}
header: Server: cloudflare
header: CF-RAY: 64c9806c3ef838b0-VIE
header: alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
2021-05-09 08:19:14 LibreELEC anime_downloader.session[1] DEBUG uncached request
2021-05-09 08:19:14 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG https://animesuge.io/ajax/anime/search?keyword=My+Hero+ACademis+5
2021-05-09 08:19:14 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG /tmp/animedluat6ak6p/tmp5hzilj7z
+--------+----------------------------------+--------+
|      5 | My Hero Academia: Two Heroes     |        |
|      4 | Hitorijime My Hero               |        |
|      3 | Hitorijime My Hero (Dub)         |        |
|      2 | Boku no Hero Academia 5th Season |        |
|      1 | My Hero Academia 5 (Dub)         |        |
|--------+----------------------------------+--------|
|   SlNo | Title                            | Meta   |
+--------+----------------------------------+--------+
Enter the anime no: [1]: 2
2021-05-09 08:19:31 LibreELEC anime_downloader.util[1] INFO Selected Boku no Hero Academia 5th Season
2021-05-09 08:19:31 LibreELEC anime_downloader.sites.anime[1] INFO Extracting episode info from page
2021-05-09 08:19:31 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
2021-05-09 08:19:31 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG GET https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z
2021-05-09 08:19:31 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {}
2021-05-09 08:19:31 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19'}
2021-05-09 08:19:31 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
send: b'GET /anime/boku-no-hero-academia-5th-season-653z HTTP/1.1\r\nHost: animesuge.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 09 May 2021 08:19:31 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d5a6b64f5bc2ccf7d9bcaf381e2bf8ceb1620548371; expires=Tue, 08-Jun-21 08:19:31 GMT; path=/; domain=.animesuge.io; HttpOnly; SameSite=Lax
header: X-Frame-Options: SAMEORIGIN
header: x-dmc: h2
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 09f1cedbb800000f92d4139000000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=HuybXozwhfAJF9Bi1cMZcMcGnDRQ6Uu4%2BTcF5n3QTlzWDOmnJ5TdeRQI6TKuIUQGfZUcQVZv%2Bf5p%2BKaHlQZEPT8forQimZI0cgB7cS8%3D"}],"group":"cf-nel","max_age":604800}
header: NEL: {"report_to":"cf-nel","max_age":604800}
header: Server: cloudflare
header: CF-RAY: 64c980d92ae30f92-VIE
header: Content-Encoding: gzip
header: alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
2021-05-09 08:19:31 LibreELEC anime_downloader.session[1] DEBUG uncached request
2021-05-09 08:19:31 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z
2021-05-09 08:19:31 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG /tmp/animedluat6ak6p/tmp20wy9bsn
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG GET https://animesuge.io/ajax/anime/servers
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'params': {'id': '653z'}}
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19'}
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
send: b'GET /ajax/anime/servers?id=653z HTTP/1.1\r\nHost: animesuge.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 09 May 2021 08:19:32 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d07e8b4ca291f34ccfe2c8de2f2b8a34f1620548372; expires=Tue, 08-Jun-21 08:19:32 GMT; path=/; domain=.animesuge.io; HttpOnly; SameSite=Lax
header: X-Frame-Options: SAMEORIGIN
header: Content-Encoding: gzip
header: x-dmc: b0
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 09f1cedeee0000fcb1973f5000000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=n9%2BsUMWKp5QTjB0tBdIU6GKxI%2FkaQ6FGmDm0BEvo%2FBDahKf5PaEYgujkpBIgxwVkrgvgajyW8SkCIE7sIyxW6YpW1DnWa6YcYtTcj2c%3D"}],"group":"cf-nel","max_age":604800}
header: NEL: {"report_to":"cf-nel","max_age":604800}
header: Server: cloudflare
header: CF-RAY: 64c980de4d66fcb1-VIE
header: alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
2021-05-09 08:19:32 LibreELEC anime_downloader.session[1] DEBUG uncached request
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG https://animesuge.io/ajax/anime/servers?id=653z
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG /tmp/animedluat6ak6p/tmpaw37fq67
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.anime[1] DEBUG EPISODE IDS: length: 7, ids: ['https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z/ep-1', 'https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z/ep-2', 'https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z/ep-3', 'https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z/ep-4', 'https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z/ep-5', 'https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z/ep-6', 'https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z/ep-7']
2021-05-09 08:19:32 LibreELEC anime_downloader.commands.dl[1] INFO Found anime: Boku no Hero Academia 5th Season
2021-05-09 08:19:32 LibreELEC anime_downloader.commands.dl[1] INFO Downloading to /downloads
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.anime[1] DEBUG Extracting stream info of id: https://animesuge.io/anime/boku-no-hero-academia-5th-season-653z/ep-1
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG GET https://animesuge.io/ajax/anime/servers
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'params': {'id': '653z', 'episode': '1'}}
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19'}
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
send: b'GET /ajax/anime/servers?episode=1&id=653z HTTP/1.1\r\nHost: animesuge.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 09 May 2021 08:19:32 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=de7f0863e4da25d8722a7302b3275d4fc1620548372; expires=Tue, 08-Jun-21 08:19:32 GMT; path=/; domain=.animesuge.io; HttpOnly; SameSite=Lax
header: X-Frame-Options: SAMEORIGIN
header: Content-Encoding: gzip
header: x-dmc: b0
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 09f1cee0d20000fc9d7d2d0000000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=yMiVgf6nMmfq1D5kqH8f7tc7GwVT6ksjnrSSSQlBJOlaWJO5I4QGkzdvIECmUai9wH4Ys6XgEkA1ywL0L%2B3Ou5j%2BAcVMGSuUnhJEJRE%3D"}],"group":"cf-nel","max_age":604800}
header: NEL: {"report_to":"cf-nel","max_age":604800}
header: Server: cloudflare
header: CF-RAY: 64c980e15c36fc9d-VIE
header: alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
2021-05-09 08:19:32 LibreELEC anime_downloader.session[1] DEBUG uncached request
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG https://animesuge.io/ajax/anime/servers?episode=1&id=653z
2021-05-09 08:19:32 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG /tmp/animedluat6ak6p/tmprtlhn5c9
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG GET https://animesuge.io/ajax/anime/episode
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'params': {'id': '76013b7a51028c7e1a9b7a7bcc8fe0998b09672605b59b17f58ca36b2da85978'}}
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19'}
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
send: b'GET /ajax/anime/episode?id=76013b7a51028c7e1a9b7a7bcc8fe0998b09672605b59b17f58ca36b2da85978 HTTP/1.1\r\nHost: animesuge.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 09 May 2021 08:19:33 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d645f7f656fccfe83b3a8cd5e0fd213401620548373; expires=Tue, 08-Jun-21 08:19:33 GMT; path=/; domain=.animesuge.io; HttpOnly; SameSite=Lax
header: X-Frame-Options: SAMEORIGIN
header: Content-Encoding: gzip
header: x-dmc: b0
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 09f1cee2cd000038bff68f0000000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=hI2vC8BQheRQq3fqB2Fu2%2F99Ze0kDCu8OZ2KqoB9LcrzljyMWWwAm2anedhHGmUPzy%2FioLReXyHZUFLUsqZUO56usF8rs34CpYti60Q%3D"}],"group":"cf-nel","max_age":604800}
header: NEL: {"report_to":"cf-nel","max_age":604800}
header: Server: cloudflare
header: CF-RAY: 64c980e47e1438bf-VIE
header: alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
2021-05-09 08:19:33 LibreELEC anime_downloader.session[1] DEBUG uncached request
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG https://animesuge.io/ajax/anime/episode?id=76013b7a51028c7e1a9b7a7bcc8fe0998b09672605b59b17f58ca36b2da85978
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG /tmp/animedluat6ak6p/tmp7o6d4645
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG GET https://animesuge.io/ajax/anime/episode
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'params': {'id': '44a260ca3ff23c0ff9a7e80f2a6ad8ce6292032d866ea6728295916880972a4e'}}
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19'}
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
send: b'GET /ajax/anime/episode?id=44a260ca3ff23c0ff9a7e80f2a6ad8ce6292032d866ea6728295916880972a4e HTTP/1.1\r\nHost: animesuge.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 09 May 2021 08:19:33 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d07b31d5440e53f1b87316d3f4574e7011620548373; expires=Tue, 08-Jun-21 08:19:33 GMT; path=/; domain=.animesuge.io; HttpOnly; SameSite=Lax
header: X-Frame-Options: SAMEORIGIN
header: Content-Encoding: gzip
header: x-dmc: b0
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 09f1cee4a90000cba05c00d000000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=ja7j4sQijpCHyEIVanz7KAeU0gbd7qe2NLqBLpE1iIJZBR%2BwDqhaIZe4rsHstoYNN9HE9kBkTixn%2BWHJrivRdXx2AJCNCPB2l8FRGE4%3D"}],"group":"cf-nel","max_age":604800}
header: NEL: {"report_to":"cf-nel","max_age":604800}
header: Server: cloudflare
header: CF-RAY: 64c980e77c43cba0-VIE
header: alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
2021-05-09 08:19:33 LibreELEC anime_downloader.session[1] DEBUG uncached request
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG https://animesuge.io/ajax/anime/episode?id=44a260ca3ff23c0ff9a7e80f2a6ad8ce6292032d866ea6728295916880972a4e
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG /tmp/animedluat6ak6p/tmp2z4pcgyy
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.anime[1] DEBUG Data : [{'extractor': 'mp4upload', 'url': 'https://www.mp4upload.com/embed-5ispl2tdpw49.html', 'server': 'mp4upload', 'version': 'subbed'}, {'extractor': 'streamtape', 'url': 'https://streamtape.com/e/lOegpyG86wS7yPv/\x14', 'server': 'streamtape', 'version': 'subbed'}]
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.anime[1] DEBUG Sorted sources : [{'extractor': 'mp4upload', 'url': 'https://www.mp4upload.com/embed-5ispl2tdpw49.html', 'server': 'mp4upload', 'version': 'subbed'}, {'extractor': 'streamtape', 'url': 'https://streamtape.com/e/lOegpyG86wS7yPv/\x14', 'server': 'streamtape', 'version': 'subbed'}]
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.anime[1] DEBUG Sources : [('mp4upload', 'https://www.mp4upload.com/embed-5ispl2tdpw49.html')]
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG GET https://www.mp4upload.com/embed-5ispl2tdpw49.html
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {}
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19'}
2021-05-09 08:19:33 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG -----
send: b'GET /embed-5ispl2tdpw49.html HTTP/1.1\r\nHost: www.mp4upload.com\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 09 May 2021 08:19:34 GMT
header: Content-Type: text/html ; charset=UTF-8
header: Content-Length: 3396
header: Connection: keep-alive
header: Set-Cookie: __cfduid=db17ba9f5fc097240d5ae45bc9ba9466a1620548374; expires=Tue, 08-Jun-21 08:19:34 GMT; path=/; domain=.mp4upload.com; HttpOnly; SameSite=Lax
header: Expires: Sat, 08 May 2021 08:19:34 GMT
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 09f1cee6a90000a7980702a000000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=uNNeG809F1QbHTxtuXCu3I1xBpjrOktFSLueE6gnxYm%2FNgUY4YNzjT8cIhtdxXtAVf%2F670bt0tTv%2FpQVf355My9yyDdraUg%2B%2B8oa2J7szg1VfA%3D%3D"}],"group":"cf-nel","max_age":604800}
header: NEL: {"report_to":"cf-nel","max_age":604800}
header: Server: cloudflare
header: CF-RAY: 64c980ea9d7aa798-IST
2021-05-09 08:19:34 LibreELEC anime_downloader.session[1] DEBUG uncached request
2021-05-09 08:19:34 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG https://www.mp4upload.com/embed-5ispl2tdpw49.html
2021-05-09 08:19:34 LibreELEC anime_downloader.sites.helpers.request[1] DEBUG /tmp/animedluat6ak6p/tmp73oun_39
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/commands/dl.py", line 140, in command
    for episode in animes:
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/sites/anime.py", line 201, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/sites/anime.py", line 298, in __init__
    try_data()
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/sites/anime.py", line 296, in try_data
    self.source().stream_url
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/extractors/base_extractor.py", line 32, in stream_url
    self.get_data()
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/extractors/base_extractor.py", line 44, in get_data
    data = self._get_data()
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/extractors/mp4upload.py", line 20, in _get_data
    script = util.deobfuscate_packed_js(script)
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/util.py", line 356, in deobfuscate_packed_js
    return eval_in_node('eval=console.log; ' + packedjs)
  File "/usr/local/lib/python3.9/site-packages/anime_downloader/util.py", line 361, in eval_in_node
    output = subprocess.check_output(['node', '-e', js])
  File "/usr/local/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'node'
~ # 
```
</details>

**Comment by queeup** [comment]
It's because of this I guess:
 - For Cloudflare scraping either cfscrape or selenium is used. Cfscrape depends on node-js and selenium utilizes an automated invisible instance of a browser (chrome/firefox). So, if you want to use Cloudflare enabled sites, make sure you have node-js and a webdriver installed.

**Comment by ArjixGamer** [comment]
Just install nodejs and make sure its on path.

**Comment by ArjixGamer** [comment]
Added it to README that it requires Nodejs

**Pull request merged**
