### PR TITLE
M3u8 support 

### PR DESCRIPTION
**Pull request by Blatzar**
Not tested on windows yet, fixes https://github.com/vn-ki/anime-downloader/issues/489

### CODE REVIEW

**Review by IguanasInPyjamas — DISMISSED** [review]
I have no issues with this.

**Comment by Blatzar** [comment]
All the fuckery because external downloader and internal downloader is treated very diffrently

**Comment by Blatzar** [comment]
Doesn't support encryption or this shit below, I'll look into them both.
I think I got encryption working, but it still wont work fully on animepahe, don't know if it's because they fuck their videos or because the decryption is lacking.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=800000,RESOLUTION=640x360
360p/360p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2800000,RESOLUTION=1280x720
720p/720p.m3u8
```

**Comment by IguanasInPyjamas** [comment]
Issue with m3u8s from searches of the form ``anime dl -u "code geass" -p animekisa -c 5 `` 

The issue comes from 'segments'. This returns an empty array inside ``self.m3u8file.get_tssegments()``, which leads to an M3u8DownloaderNoStreamException().

**Pull request closed without merging**
