### PR TITLE
chore: update docs: link people to anime-dl/anime-downloader (#718)

### LINKED ISSUE #718: Docs refer to vn-ki/anime-downloader even though it has moved to anime-dl/anime-downloader
**Describe the bug**
Docs refer to vn-ki/anime-downloader even though it has moved to anime-dl/anime-downloader

**To reproduce**
Visible at:
https://anime-downlader.readthedocs.io/en/latest/usage/installation.html and multiple other locations

### PR DESCRIPTION
**Pull request by sreekaransrinath**
Closes #718

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
is there a reason for using a custom hash position rather than letting the title be used instead?
image

**Comment by ArjixWasTaken** [comment]
code of conduct is an illusion
image

**Comment by ArjixWasTaken** [comment]
I don't think any of us follow that scheme here.
image

**Comment by ArjixWasTaken** [comment]
Fix those two issues and I'll merge.

**Comment by sreekaransrinath** [comment]
> I don't think any of us follow that scheme here. image
> 
> For commit messages you should try to briefly describe the changes/fixes you did.

Fair enough, I wanted to introduce a template that could be edited per needs

**Comment by sreekaransrinath** [comment]
> code of conduct is an illusion image
LOL
> 
> I guess you meant to add one but forgot to?

**Comment by sreekaransrinath** [comment]
There ya go -- removed CoC for now, I'll add it in later when I get a feel for how this project treats different actions (as opposed to pulling from a template)

**Comment by ArjixWasTaken** [comment]
Looks good to go.

**Pull request merged**
