### PR TITLE
added wget as an external download manager

### PR DESCRIPTION
**Pull request by ArjixGamer**
wget cant create directories that we specify, it can only create its own url scraped directories which is not desired, so for now it will only download to the Current Working Directory. While the download path doesnt work as desired, we can pass the referer to make it work with providers that require a referer, any ideas on how to get the download dir working are welcome

### CODE REVIEW

**Comment by Blatzar** [comment]
I thought anime dl made the directories needed, I've at least seen some function in utils to make directory or something similar.

**Comment by ArjixGamer** [comment]
> I thought anime dl made the directories needed, I've at least seen some function in utils to make directory or something similar.

it does to an extent, but we also make a directory with file_format

**Comment by Blatzar** [comment]
Doesn't seem to work on twist :/

**Comment by AbdullahM0hamed** [comment]
UPDATED: now works on twist, and download path is created prior to downloading with wget

**Review by IguanasInPyjamas — COMMENTED** [review]
not relevant

**Comment by AbdullahM0hamed** [comment]
@IguanasInPyjamas this doesn't touch idm in any way. Wget has Linux supports, and I've tested that it works on android

**Comment by IguanasInPyjamas** [comment]
> @IguanasInPyjamas this doesn't touch idm in any way. Wget has Linux support, and I've tested that it works on android

OOPS, yeah I got confused in my head. Lemmie delete that

**Comment by IguanasInPyjamas** [comment]
I'll test wget on Linux, can someone test wget on windows? then I'll move to merge

**Comment by nate-moo** [comment]
got it for windows

**Comment by nate-moo** [comment]
it doesn't work

**Comment by nate-moo** [comment]
image
works

**Comment by IguanasInPyjamas** [comment]
Works on Linux and twist. Moving to merge

**Pull request merged**
