### PR TITLE
Kwik Fixes

### PR DESCRIPTION
**Pull request by nate-moo**
fixes later parts of #412
animepahe returns a m3u8 so it isn't too helpful when downloading but ffmpeg can convert it to an mp4 with:

```
ffmpeg -headers "Referer: https://kwik.cx/" -i {link goes here} -c copy anime.mp4
```

### CODE REVIEW

**Comment by ArjixGamer** [comment]
wait before merging
ill suggest a change (will take me like 20 mins at most)

**Comment by ArjixGamer** [comment]
actually go ahead, ill make another PR
(since I cant push to your fork)

**Comment by ArjixGamer** [comment]
I suggest changing the title to "Fixed kwik & AnimePahe".

**Comment by nate-moo** [comment]
But Kwik fixes is a pun and adding other stuff makes it less punny

**Comment by ArjixWasTaken** [comment]
Thx to @justfoolingaround for the fix.

**Pull request merged**
